### ISSUE TITLE
Search - Cannot read property 'width' of null

### ISSUE THREAD

**Issue by italocassio** [PDFTron/webviewer-vue-sample#15]
Hello guys!

In version 7.0.0, when the search finds the keyword on the last page, an error occurs, breaking the search function.
In this case, my pdf has **46 pages**.

`Uncaught TypeError: Cannot read property 'width' of null
    at r.f.wo (CoreControls.js:267)
    at ba.VX (CoreControls.js:331)
    at ba.fe (CoreControls.js:330)
    at ba.Qf (CoreControls.js:359)
    at searchListener (WebViewer.vue?197a:70)
    at webviewer-ui.min.js:50
    at Array.forEach (<anonymous>)
    at a.runSearchListeners (webviewer-ui.min.js:50)
    at Object.f (webviewer-ui.min.js:50)
    at r (CoreControls.js:273)`

`CoreControls.js:189 Attempting to get page matrix for page 47 that doesn't exist.`

`Uncaught (in promise) TypeError: Cannot read property 'inverse' of null
    at h.At (CoreControls.js:1858)
    at h.QO (CoreControls.js:1861)
    at CoreControls.js:354`

**Comment by mparizeau-pdftron** [comment]
Is there some extra code you're using to reproduce the issue? 

I tried reproducing by loading this sample from our website https://www.pdftron.com/samples/web/samples/viewing/viewing/ and then in the search panel searched for "vendor" which has results on the last page. In the console I don't see any errors.

Do you see any errors from searching on that sample?

**Comment by italocassio** [comment]
Hi, @mparizeau-pdftron! Thanks for answering :)

Yes, I'm using the function searchTextFull. After the moment implement the [Searching Text in PDF Documents using JavaScript](https://www.pdftron.com/documentation/web/guides/text-search?searchTerm=searchListener) (I just copy and past the code)  the bug happens. After that the search for keywords stops working.

The error is more specifically in the document load event.

`WebViewer(
        {
          path: this.path,
          initialDoc: this.url // replace with your own PDF file
        },
        this.$refs.viewer
      ).then(instance => {
        const { annotManager, docViewer, Annotations } = instance;

        const searchListener = (searchPattern, options, results) => {
          // add redaction annotation for each search result
          const newAnnotations = results.map(result => {
            const annotation = new Annotations.RedactionAnnotation();
            annotation.PageNumber = result.page_num + 1;
            annotation.Quads = result.quads.map(quad => quad.getPoints());
            annotation.StrokeColor = new Annotations.Color(136, 39, 31);
            return annotation;
          });

          annotManager.addAnnotations(newAnnotations);
          annotManager.drawAnnotationsFromList(newAnnotations);
        };

        docViewer.on("documentLoaded", () => {
          const searchPattern = "";
          // searchPattern can be something like "search*m" with "wildcard" option set to true
          // searchPattern can be something like "search1|search2" with "regex" option set to true

          // options default values are false
          const searchOptions = {
            caseSensitive: true, // match case
            wholeWord: true, // match whole words only
            wildcard: false, // allow using '*' as a wildcard value
            regex: false, // string is treated as a regular expression
            searchUp: false, // search from the end of the document upwards
            ambientString: true // return ambient string as part of the result
          };

          instance.addSearchListener(searchListener);
          // start search after document loads
          instance.searchTextFull(searchPattern, searchOptions);
        });
      });`

In the example you sent, the bug did not happen.

**Comment by mparizeau-pdftron** [comment]
Ah I see. I think the problem is with the documentation not being correct for version 7.0.  I think you'll want to have `annotation.PageNumber = result.pageNum;`

I'll update the documentation to fix this.

**Comment by italocassio** [comment]
Thanks @mparizeau-pdftron  for your attention. I'm waiting for the documentation to be updated.
For now I will go back to version 6.3.6 that the code above is working.

**Comment by mparizeau-pdftron** [comment]
Hi @italocassio the guide should have already been updated for 7.0 https://www.pdftron.com/documentation/web/guides/text-search/ let me know if you're still seeing any issues with it.
