### ISSUE TITLE
Add tag vue2 

### ISSUE THREAD

**Issue by abhimanusharma** [PDFTron/webviewer-vue-sample#17]
I need to implement this in my existing app created in vue2. I want support of this to implement with vue2.

**Comment by CorreyL** [comment]
Hello @abhimanusharma,

Correy here from PDFTron, thanks for the heads up about Vue 2 compatibility, we'd be happy to make a tag/branch that is specific to Vue 2 support.

The sample should be compatible with Vue 2 at this commit:

https://github.com/PDFTron/webviewer-vue-sample/tree/24de7f45d85caa047f5b8ee0c297492a829464be

Please feel free to let me know if you're running into any Vue 2 specific issues and we'd be happy to help.

Best regards,
- Correy

**Comment by CorreyL** [comment]
Hello @abhimanusharma,

I'm going to close up this ticket, but feel free to let us know if you have any follow-up questions about Vue2 support.
