### ISSUE TITLE
Not previewing any file.

### ISSUE THREAD

**Issue by akeshj** [PDFTron/webviewer-vue-sample#18]
I am download code sample from git ,After that I install npm and run code .Its launch it preview the default file after that I change the file path for my file but it not previewing giving following error "The file is not linearized." But I download electron framework sample code from github and try for same file it preview then what is the problem with vue please help me.

**Comment by mparizeau-pdftron** [comment]
It might depend on how you're referencing the file in the Vue sample. Could you create a fork of this repo that references your file and doesn't seem to load? Then we can take a closer look at it.

**Comment by andreysaf** [comment]
Hey @akeshj, let us know if this is still an issue for you.
