### ISSUE TITLE
How to show docx files

### ISSUE THREAD

**Issue by robertnicjoo** [PDFTron/webviewer-vue-sample#19]
Whatever I am trying it does not load `docx` file is there any catch to that? is it just show `PDF` files?

**Comment by andreysaf** [comment]
Hey @robertnicjoo ! Sorry, we have missed the issue over the holidays. Just wanted to follow up and see if you still having issues.

For DOCX, you can just pass the document either into `initialDoc` property of WebViewer options object or into `instance.loadDocument(pathToDocx, { extension: 'docx' })`.
