### ISSUE TITLE
在自己的vue项目中要使用pdfTron这个库,需要安装哪些包?(What packages need to be installed to use the pdftron Library in your own vue project)

### ISSUE THREAD

**Issue by TJX666666** [PDFTron/webviewer-vue-sample#4]
package.json config:
`"scripts": {
    "dev": "vue-cli-service serve",
    "build:prod": "vue-cli-service build",
    "build:stage": "vue-cli-service build --mode staging",
    "preview": "node build/index.js --preview",
    "lint": "eslint --ext .js,.vue src",
    "test:unit": "jest --clearCache && vue-cli-service test:unit",
    "test:ci": "npm run lint && npm run test:unit",
    "svgo": "svgo -f src/icons/svg --config=src/icons/svgo.yml",
    "postinstall": "npm run download-webviewer",
    "download-webviewer": "npx @pdftron/webviewer-downloader"
  },
  "dependencies": {
    "@ckeditor/ckeditor5-build-decoupled-document": "^12.4.0",
    "@ckeditor/ckeditor5-vue": "^1.0.0",
    "@icony/vue-container": "^1.0.6",
    "element-ui": "^2.12.0",
    "epubjs": "^0.3.73",
    "jquery": "^3.4.1",
    "jszip": "^2.6.1",
    "md5": "^2.2.1",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "path-to-regexp": "2.4.0",
    "plyr": "^3.5.6",
    "swiper": "^4.5.0",
    "vue": "^2.6.11",
    "vue-cropper": "^0.4.9",
    "vue-plyr": "^6.0.4",
    "vue-ueditor-wrap": "^2.4.1",
    "vue-video-player": "^5.0.2",
    "core-js": "^3.4.8"
  },
  "devDependencies": {
    "@babel/core": "7.0.0",
    "@babel/register": "7.0.0",
    "@vue/cli-plugin-babel": "3.6.0",
    "@vue/cli-plugin-eslint": "3.6.0",
    "@vue/cli-plugin-unit-jest": "3.6.3",
    "@vue/cli-service": "3.6.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "autoprefixer": "^9.5.1",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "10.0.1",
    "babel-jest": "23.6.0",
    "chalk": "2.4.2",
    "connect": "3.6.6",
    "cz-conventional-changelog": "^3.0.2",
    "eslint": "5.15.3",
    "eslint-plugin-vue": "5.2.2",
    "html-webpack-plugin": "3.2.0",
    "mockjs": "1.0.1-beta3",
    "node-sass": "^4.9.0",
    "runjs": "^4.3.2",
    "sass-loader": "^7.1.0",
    "script-ext-html-webpack-plugin": "2.1.3",
    "script-loader": "0.7.2",
    "serve-static": "^1.13.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "svg-sprite-loader": "4.1.3",
    "svgo": "1.2.2",
    "vue-i18n": "^8.15.0",
    "vue-template-compiler": "^2.6.11"
  },`

把下载好的webviewer.zip的lib文件夹放到了public下 并在组件中引入 仍然不能正常显示,为什么呢?
Put the Lib folder of downloaded webviewer.zip under public and introduce it into the component, but it still can't be displayed normally. Why?

**Comment by mparizeau-pdftron** [comment]
What error are you seeing in the console?

It might be that the "path" option on WebViewer isn't pointing to the correct location of WebViewer's lib folder inside of your app.

**Comment by TJX666666** [comment]
> What error are you seeing in the console?
> 
> It might be that the "path" option on WebViewer isn't pointing to the correct location of WebViewer's lib folder inside of your app.

thanks for your concern , I failed to install online through NPM, finally , I downloaded the offline package and put it in public successfully .
