### ISSUE TITLE
Position canvas not correct with version 11.0.0

### ISSUE THREAD

**Issue by huynhlv** [PDFTron/webviewer-vue-sample#56]
I'm using this version 
![image](https://github.com/user-attachments/assets/f9654691-4f2e-4d28-b814-7cb39d368f19)
I got a issue below, seems a canvas not align to center(works well with default v10.0.0 version)
![2024-11-19_18-57](https://github.com/user-attachments/assets/944ab3c2-fa7b-4a3f-9926-cd498b3a0b83)
Can you help me explain why that's not work. Where should I need to update? Thank you so much!

**Comment by huynhlv** [comment]
Hi @mparizeau-pdftron, I’m stuck on this issue. Could you help me out? I’d really appreciate it.

**Comment by mparizeau-pdftron** [comment]
It looks like this is an issue when using the web component version of WebViewer for some reason. We'll investigate, but for now you can use `WebViewer.Iframe` with the WebViewer constructor.
```
WebViewer.Iframe({
  path: ...
// other options
})
```

**Comment by huynhlv** [comment]
@mparizeau-pdftron Thank you for your support, I will use `Iframe` of WebViewer
