### ISSUE TITLE
The document does not load on Firefox

### ISSUE THREAD

**Issue by remideneleaodocs** [PDFTron/webviewer-vue-sample#6]
The document never loads in the WebViewer on Firefox. The progress bar is displayed but nothing happens then, and there is no error in the dev console (see screenshot).

We tested on Chrome and Edge 80, all is working as expected.
We also tried to load a PDF document in our own Vue app and got the same result (working on Chrome / Edge but not on Firefox).
And we finally tried with your [webviewer-typescript-sample](https://github.com/PDFTron/webviewer-typescript-sample) and it's working on all browsers.

So it seems to be a Vue.js + Firefox issue.

Step to reproduce:

1. Checkout the code
2. Run `npm install`
3. Run `npm run serve`
4. Open Mozilla Firefox (tested on versions 73 and 74)

![image](https://user-images.githubusercontent.com/8693949/76412545-13664300-6394-11ea-99ea-43cbed73a455.png)

**Comment by mparizeau-pdftron** [comment]
Hmm, I'm having trouble reproducing this. I just tried running through your steps using Firefox 74 on both Windows and Mac and the document is able to load for me without any issues.

One difference is that version 6.2 has been released now and this sample is now automatically using that. Maybe try using version 6.2 and see if that makes a difference for you.

**Comment by remideneleaodocs** [comment]
I can confirm that it is reproductible with version 6.1.1 but not with with version 6.2.
Thanks!
